<?php

class UsersSeeder
{
    public function run(): string
    {

        return "INSERT INTO users (id, username, first_name, last_name, other_name, phone_number, email, remember_token, password, created_at, updated_at) VALUES ('Sample id 0', 'Sample username 0', 'Sample first_name 0', 'Sample last_name 0', 'Sample other_name 0', 'Sample phone_number 0', 'Sample email 0', 'Sample remember_token 0', 'Sample password 0', 'Sample created_at 0', 'Sample updated_at 0'), ('Sample id 1', 'Sample username 1', 'Sample first_name 1', 'Sample last_name 1', 'Sample other_name 1', 'Sample phone_number 1', 'Sample email 1', 'Sample remember_token 1', 'Sample password 1', 'Sample created_at 1', 'Sample updated_at 1'), ('Sample id 2', 'Sample username 2', 'Sample first_name 2', 'Sample last_name 2', 'Sample other_name 2', 'Sample phone_number 2', 'Sample email 2', 'Sample remember_token 2', 'Sample password 2', 'Sample created_at 2', 'Sample updated_at 2'), ('Sample id 3', 'Sample username 3', 'Sample first_name 3', 'Sample last_name 3', 'Sample other_name 3', 'Sample phone_number 3', 'Sample email 3', 'Sample remember_token 3', 'Sample password 3', 'Sample created_at 3', 'Sample updated_at 3'), ('Sample id 4', 'Sample username 4', 'Sample first_name 4', 'Sample last_name 4', 'Sample other_name 4', 'Sample phone_number 4', 'Sample email 4', 'Sample remember_token 4', 'Sample password 4', 'Sample created_at 4', 'Sample updated_at 4'), ('Sample id 5', 'Sample username 5', 'Sample first_name 5', 'Sample last_name 5', 'Sample other_name 5', 'Sample phone_number 5', 'Sample email 5', 'Sample remember_token 5', 'Sample password 5', 'Sample created_at 5', 'Sample updated_at 5'), ('Sample id 6', 'Sample username 6', 'Sample first_name 6', 'Sample last_name 6', 'Sample other_name 6', 'Sample phone_number 6', 'Sample email 6', 'Sample remember_token 6', 'Sample password 6', 'Sample created_at 6', 'Sample updated_at 6'), ('Sample id 7', 'Sample username 7', 'Sample first_name 7', 'Sample last_name 7', 'Sample other_name 7', 'Sample phone_number 7', 'Sample email 7', 'Sample remember_token 7', 'Sample password 7', 'Sample created_at 7', 'Sample updated_at 7'), ('Sample id 8', 'Sample username 8', 'Sample first_name 8', 'Sample last_name 8', 'Sample other_name 8', 'Sample phone_number 8', 'Sample email 8', 'Sample remember_token 8', 'Sample password 8', 'Sample created_at 8', 'Sample updated_at 8'), ('Sample id 9', 'Sample username 9', 'Sample first_name 9', 'Sample last_name 9', 'Sample other_name 9', 'Sample phone_number 9', 'Sample email 9', 'Sample remember_token 9', 'Sample password 9', 'Sample created_at 9', 'Sample updated_at 9')";

    }
}